server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc_ad_data?autoReconnect=true
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

feign: #fei  服务调用
  hystrix:
    enabled: true

management: #启动  监控信息  服务监控
  endpoints:
    web:
      exposure:   #暴露信息
        include: "*"    #暴露全部信息

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    binlogName: binlog.000038
    position: 60451

  kafka:
    topic: ad-search-mysql-data
